### ISSUE TITLE
Add "Develop" menu

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#10]
New menu button on the front page with some link buttons:
- Link to Modding Guide wiki page
- Link to Contributor Guide wiki page on GitHub
- Link to Dev Setup wiki page
- Link to Contributor Intro forum
- Link to download latest develop zip ball from MovingBlocks/Terasology (https://github.com/MovingBlocks/Terasology/archive/develop.zip)

**Comment by nnsdev** [comment]
Added.

**Comment by Cervator** [comment]
I see the files, but the "Develop" button doesn't seem to work - it doesn't open the menu page :-(

**Comment by nnsdev** [comment]
Now it should work.

**Comment by 3000Lane** [comment]
http://www.xup.in/dl,20459369/Button.zip/
The Buttons

**Comment by Cervator** [comment]
Yep, I can get into the menu now. Top button appears broken for me though.
