### ISSUE TITLE
Add a github link.... somewhere....

### ISSUE THREAD

**Issue by Luraktinus** [MovingBlocks/legacy-website#103]
....maybe???

**Comment by Cervator** [comment]
So there used to be a more obvious one on terasology.org in its former edition. Current one is more player-centric with the intend to have a similarly developer-centric version. But until that's in place it may indeed be wise to have some more relevant links :-)

Pinging @smsunarto for reference

**Comment by Luraktinus** [comment]
well, that might more sense if the bugs i pointed out that make the game unplayable gets fixed

**Comment by Cervator** [comment]
Respectfully, while the game may be unplayable for you (do you have some links to detailed issues you've submitted?), it is most definitely playable by most who try. We're happy to improve it further but a positive attitude on both sides goes a long way :-)

**Comment by Cervator** [comment]
Closing in favor of #103 which will probably get picked up soon
