### ISSUE TITLE
Add a GitHub icon link in the site footer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#107]
We usually have one, for some reason on the latest iteration of the splash site one isn't yet present.

Should be fairly easy: copy the associated code for one of the existing footer icons, add a new one with some GitHub graphic from a branding pack somewhere. Link to https://github.com/MovingBlocks/Terasology

**Comment by RupeshGoud** [comment]
I will take it

**Comment by diproray** [comment]
I would like to work on this issue!

**Comment by Cervator** [comment]
Heya @RupeshGoud and welcome - this was a quick one, there's already a PR sent in for a fix :-)
