### ISSUE TITLE
Replace "End" button with "Play!"

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#11]
Probably put the bottom at the top to. Direct link to the applet - http://blog.movingblocks.net/applet/index.html

Incidentally we probably need to consider a fallback hosting option for said applet if the main server is unavailable, hmm. We used to be able to run it straight out of Jenkins, wonder if you could run it right from GitHub as a page somehow ;-)

(that's out of scope for this issue though, just thinking out loud ..)

**Comment by nnsdev** [comment]
Link and Image made, you can download a font, like @3000lane used, when you're searching in Google.

**Comment by Cervator** [comment]
If we have the applet included on the splash site on its own "page" then that'd be even better :-)

**Comment by Cervator** [comment]
#14 didn't seem to change this, I still get the "End" button but now it doesn't do anything?

**Comment by nnsdev** [comment]
Now it works, i forgot to change the button and the link in "index_content.html" :)

**Comment by 3000Lane** [comment]
I upload the button.psd and the font :)
Link http://www.xup.in/dl,69448357/ButtonPSD.zip/

**Comment by nnsdev** [comment]
Many Thanks 300lane now i can make the buttons :)

**Comment by 3000Lane** [comment]
Have fun but pls use sprites :p

**Comment by nnsdev** [comment]
@3000Lane how did you make the black border?

**Comment by 3000Lane** [comment]
Text-FX in Photoshop

**Comment by nnsdev** [comment]
Damn, I don't have Photoshop.

**Comment by 3000Lane** [comment]
What for buttons you need ;)
i can make it for you

**Comment by nnsdev** [comment]
Develop,Play,Latest Dev-Build,Contributor Guide,Contributor Intro, Dev Setup and Modding Guide :)

**Comment by 3000Lane** [comment]
here the buttons :P http://www.xup.in/dl,20459369/Button.zip/

**Comment by ghost** [comment]
Thanks, will add later :-)

**Comment by Cervator** [comment]
I see em - uploaded as a test since I don't get buttons in Firefox locally: http://nanoware.org/test/

The new buttons seem "darker" somehow, unless that's an illusion from there just being more text, or maybe the font size is larger?

Thanks for coming back and helping out, by the way :D
