### ISSUE TITLE
Change / add screenies

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#12]
- [ ] Keep bg3 and bg4 IMHO - could keep the others too and make a larger rotation, but for sure we need the additional ones here
- [ ] Add at least one with everything on graphics max including lightshafts and water
- [x] Add one from Skaldarnar's gothic village (forum/fb probably has good candidates)
- [ ] Add one showing working oreons (might be one in the forum)
- [ ] Add one showing several active portals with some gelcubes bouncing around
- [x] Maybe one showing an active crafting recipe with the thought bubble visible?

**Comment by nnsdev** [comment]
Added 2 new Images, i will add more later.

**Comment by Cervator** [comment]
Two down, few more to go :-)

**Comment by nnsdev** [comment]
Didn't find (good) photos with oreons/active portals?

**Comment by Cervator** [comment]
Make some :D

Also, you might want to compress the files a little better, the two new ones in particular are pretty big (half meg isn't much on broadband but might suck on a phone or weak connection)

**Comment by nnsdev** [comment]
It's pretty hard with a laptop where I have ~3-4 FPS :D
