### ISSUE TITLE
Re-add a bit of GitHub branding?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#13]
Should we consider re-adding one or more of the GitHub branding touches on the splash site? Such as:
- "Fork me on GitHub" visible on the site they highlight as an example: http://tom.preston-werner.com - probably my favorite option
- "View on GitHub" button in the standard generated site - visible example at http://dl.terasology.org/ (which goes to the gh-pages branch in MovingBlocks/Terasology which I'll be deleting soon)
- Zip etc buttons along the edge somewhere? (also visible in one example on the link above)

I'm not _sure_ we want to do this, but something subtle (beyond just the GitHub social icon) might be a nice touch. Thoughts? :-)

**Comment by nnsdev** [comment]
Looking later where its cool :-)

**Comment by nnsdev** [comment]
Okay, i implemented "View on Github" :)

**Comment by Cervator** [comment]
I see it! Good to have a little branding back. With two buttons going to the exact same place, maybe we should change the social button GitHub to go simply to https://github.com/MovingBlocks ?

Turns out there is a whole bunch of the ribbon style logos: https://github.com/blog/273-github-ribbons - I wonder how the green one would look? Not sure which would be better :-)

**Comment by nnsdev** [comment]
Okay, @Cervator, added Green Ribbon with Link to https://github.com/MovingBlocks :)
