### ISSUE TITLE
Re-add a dismissable banner background to the IE disclaimer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#16]
This is an optional follow-up to #4 - the original IE disclaimer banner by @3000Lane could be dismissed, and I'd love to see that working again (it was not working by the time we had made some initial changes, not sure what broke it)

@3000Lane - would you be up for tweaking that? :)

Could add the warning icon to the left as well, so long as it remains comparably small like the other icons. Banner probably shouldn't be too wide either, lest it hit the GitHub ribbon

**Comment by nnsdev** [comment]
I can do but I need an image :D

**Comment by Cervator** [comment]
Doesn't need to be fancy - just not too big or obnoxious. Anything that fits in well should work. Can be something single color, maybe with a slight border and some browser icons.

**Comment by nnsdev** [comment]
Or we could change the Terasology Banner to Don't use IE :DDD

**Comment by Cervator** [comment]
No ;-)

When you run an inclusive international project you do it right - everybody is welcome. That's why I just wanted to make the initial banner a tad milder and encouraging :-)

**Comment by nnsdev** [comment]
That was a Joke :D 
Yeah I'm searching for a picture we can use.
