### ISSUE TITLE
link blog syndication (rss/atom) feed from main page

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/legacy-website#169]
Apparently an atom feed exists as https://terasology.org/feed.xml  
but isn't discoverable from the main terasology.org landing page.

Heck, it's getting hard to find good documentation sources on feed syndication these days, it's been so long since it was in fashion.

The HTML spec has some mention of it for `link`: https://html.spec.whatwg.org/multipage/links.html#rel-alternate

**Comment by remram44** [comment]
Found this issue after checking the source code for any mention of "feed", "rss", or "atom". Adding a `<link>` to the HTML would already help a lot.
