### ISSUE TITLE
Make the logo "hide everything" action pop up a dismissable disclaimer?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#18]
@3000Lane - finally realized that fade is a feature, not a bug, hehe. Pretty cool, actually, since then you can have the screenies rotate on the screen without anything getting in the way :-)

Is there any way to pop up a little banner like the IE disclaimer that says "Clicking the logo fades out everything except the background! Click it again to bring stuff back" or something?

**Comment by Cervator** [comment]
Addition: Is it possible to include the GitHub "fork me" banner in the fade effect?

**Comment by Cervator** [comment]
Suddenly realized there's a easier change. Rather than have the logo fade made a little fade icon in a corner somewhere and use that to fade instead, leaving the logo normal and passive :-)

**Comment by nnsdev** [comment]
Of course,  its just a simple addition: alt="text" and title="text" into the IMG tag, will do when on computer.

**Comment by Cervator** [comment]
Part one is done, leaving this open for part two - a little icon in a bottom corner that'll do the fade instead of the "Terasology" logo

**Comment by nnsdev** [comment]
Doing when I'm at home at Sunday :-)

**Comment by neoascetic** [comment]
Fixed via e8b12d4?
