### ISSUE TITLE
Update "Gameplay" menu

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#21]
Button-links should go to player-guide type stuff, like:
- [ ] https://github.com/MovingBlocks/Terasology/wiki/Key-Bindings
- [ ] https://github.com/MovingBlocks/Terasology/wiki/Console-Help

There are a couple more uncreated pages in the wiki to help the player that we should fill in and link sometime ...

Video links (hard dependency on #20 to post them as tiny thumbnails in side columns)
- [x] http://www.youtube.com/watch?v=H3qItsrpceY&feature=youtu.be - Gronkh
- [x] http://www.youtube.com/watch?v=E4TbqZ0TMXg - Droide
- [x] http://www.youtube.com/watch?v=eLonNWP93h0 - Shadows
- [x] http://www.youtube.com/watch?v=9kP97RCahqc - Water
- [x] http://www.youtube.com/watch?v=yXcHe1NL1uE - Style
- [x] http://www.youtube.com/watch?v=-cdhxguyMpA - Crafting
- [x] http://www.youtube.com/watch?v=H8-afb0yUoc - Leap

I'm sure there are more videos - suggest away! Also should add #9 here when ready

**Comment by nnsdev** [comment]
Then we need @3000Lane 's Help for the "Key Bindings" & "Console Help", because I don't have Photoshop.
I can put in the other :)

**Comment by Cervator** [comment]
Ideally we'd just figure out #3 then we no longer need to make buttons, just assign text to a blank one :-)
