### ISSUE TITLE
Need new "how to" video for going through Dev Setup to run from source

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#23]
We need a new fresh one with the latest details. Akin to some of the steps @AWFeldick goes through in the block shape tutorials, but more generic and detailed. Then add it to the Development section
##

**Comment by nnsdev** [comment]
Eventually when Im back At home :-)

**Comment by smsunarto** [comment]
@Cervator do you have the link to the dev setup videos from Google Code-In? That might resolve this issue.

**Comment by skaldarnar** [comment]
General Setup: https://www.youtube.com/user/TerasologyDevTuts

Setup for Eclipse: https://www.youtube.com/watch?v=WMqGx9f28uM

For the launcher: https://www.youtube.com/watch?v=GhZF6AKIPUU

**Comment by skaldarnar** [comment]
The whole dev setup is quite in flux these days. We recently updated the engine's wiki pages, including a new page about https://github.com/MovingBlocks/Terasology/wiki/Supported-Development-Workflows.
