### ISSUE TITLE
Add WordPress site button for Begla's original blog

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#24]
At http://blog.movingblocks.net/blog/ with a WP icon of some sort :-)

Anybody able to think of other sites we should link like that? MOAR BUTON! :D

**Comment by nnsdev** [comment]
Slowly its getting full :-D

**Comment by nnsdev** [comment]
Added.

**Comment by Cervator** [comment]
Closed as complete! In a slightly belated fashion.
