### ISSUE TITLE
Auto-refresh main page after applet launches in separate window

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#29]
If possible, so we don't leave the user's main window with a big white hole in the middle :-)

**Comment by nnsdev** [comment]
Bit work.
You have to click on the applet to start it, so redirecting is working with JavaScript/PHP but I can't make it after you click on the applet.

**Comment by Cervator** [comment]
Yeah as said, no sure how doable it is. I still wonder if there isn't some sneaky way to do it, even if it takes loading the applet differently :-)

**Comment by nnsdev** [comment]
I think It's possible to include a redirect INTO the applet?

**Comment by Cervator** [comment]
As long as it works and looks nice :-)

Current approach works, so it isn't super duper critical. More of a cosmetic issue.

I'm wanting to add a Google Analytics snippet to the applet's index.html so we should probably keep using it somehow

**Comment by nnsdev** [comment]
Eventually we could use Javascript & the sleep function. But then we have problems because of different PC's.

**Comment by AnonymousMeerkat** [comment]
Here is one possible way: http://stackoverflow.com/a/5810548/999400

So you'll have to edit the code of Terasology itself, so that it will send a javascript function call once it's loaded, and then that javascript will refresh the page, or whatever it does.

**Comment by Cervator** [comment]
That sounds like potential. Adding a "hook" that you can choose to tie something to, or leave alone

**Comment by nnsdev** [comment]
I could make it that The applet launches in a New window so The Main page would be open all the time

**Comment by Cervator** [comment]
@NowNewStart - keep in mind that the applet _already_ launches in a new window. Trick is that the splash site is updated by Ajax to trigger loading of the applet which happens in the center of the splash site. When it is ready the applet pops out but the Ajax doesn't retrigger a load of, say, the main menu.

At least that's my understanding, @MiJyn is the expert :-)

If you can come up with a demo of a blank applet within the same framework that works like desired feel free!

**Comment by Cervator** [comment]
Closing this - the "hole" has shown the game log for some time now, which is even better.
