### ISSUE TITLE
Change buttons to be made by superimposing text on a blank button image

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#3]
I figure this is possible, if not easy considering all the magic already in use on the page :D

Would remove the need to make custom buttons for everything

~~An alternative graphic as a header to group things instead of being a button could be useful as well~~

**Comment by Cervator** [comment]
~~Linking to #8 which is the one that could use a category header thing~~

**Comment by nnsdev** [comment]
Can you please define me how you mean this? :)

**Comment by Cervator** [comment]
Rather than a "play.jpg" button that includes text, use some sneaky html wizardry to have text float on top of a blank button. I'm sure there some way to do it with divs, or css, or something fancy, but I have no clue exactly how :D

Maybe @MiJyn or @3000Lane know some tricks :-)

I figure it would just make maintenance easier not having to make exact buttons

**Comment by AnonymousMeerkat** [comment]
@Cervator Yes, very good idea! Probably will be something with "text-shadow" or something... "text-align:center"... hmm... I'll see what I can do tomorrow :D **EDIT**: Yeah, not exactly "tomorrow", sorry about that... I'll see what I can do... _soon_ XD
