### ISSUE TITLE
Add optional music to site featuring ChrisK's soundtrack

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#31]
Not enabled by default, of course, since everybody loves automatic HTML music amirite?

Probably a little note icon somewhere that turns it on and off, if not showing/hiding a tiny media player probably including a link to the soundtrack somewhere else.

Would also be handy for a static display of Terasology at possible future events ... ;-)

**Comment by AnonymousMeerkat** [comment]
> Not enabled by default, of course, since everybody loves automatic HTML music amirite?

Well, not everybody (I'm included in that "not everybody" category), but sure, if it's disabled by default, seems like an absolutely splendid idea!

> Probably a little note icon somewhere that turns it on and off, if not showing/hiding a tiny media player probably including a link to the soundtrack somewhere else.

Where would this be placed?

> Would also be handy for a static display of Terasology at possible future events ... ;-)

You just confused the heck out of me :P

**Comment by Cervator** [comment]
I may have injected some overly subtle sarcasm into my first sentence :D

Dunno what placement would work well, Wonder if Soundcloud has a widget you can add to sites? Ideally it would be a tiny musical note icon in a corner that would "roll out" into a small media player or something like that.

For displays I mean if Terasology is being showcased at some physical location, it would be nice to be able to leave the splash site up on a monitor with the GUI elements hidden, just flipping through nice screenies and playing music :D

**Comment by AnonymousMeerkat** [comment]
> I may have injected some overly subtle sarcasm into my first sentence :D 

Oh, haha XD Sorry, I'm really tired these days, I don't catch things like that as easily now lol

> Dunno what placement would work well, Wonder if Soundcloud has a widget you can add to sites? Ideally it would be a tiny musical note icon in a corner that would "roll out" into a small media player or something like that.

See this: https://soundcloud.com/pages/widgets . So maybe once the person hovers over the "social icon", it would roll out into the fully-featured widget?

> For displays I mean if Terasology is being showcased at some physical location, it would be nice to be able to leave the splash site up on a monitor with the GUI elements hidden, just flipping through nice screenies and playing music :D

Ohh, okay, I see!

**Comment by Cervator** [comment]
Yeah something like that. The tiny social icon is great (although I wish it looked more obviously music related, people unfamiliar with Soundcloud might have no clue), but the big play widget is monstrous :D

I wish the little five-icon thing that shows on a piece on-hover was available, with play, like, download, etc. Title too would be great.

**Comment by neoascetic** [comment]
Absolutely awesome idea!
