### ISSUE TITLE
To footer or not to footer, that is the question?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#34]
In follow-up to PR #33 

Come to think of it - do we actually _need_ a footer at all? Looking around a bit a ton of splash site / splash pages have no footer in the first place.

We can put author and copyright info in comments like in the rest of the code. I know it is nice to see your own name in a place like that, but then we don't have anything like that in the game itself, just in the credits section here on GitHub :-)

@NowNewStart + @MiJyn + @3000Lane - would the three of you be okay with attribution in comments instead? One tricky situation is having to add more and more visible names (me and @begla have made edits too but haven't added our names)

Still need to sort out the exact copyright / attribution stuff, but then we probably should add an entire "Credits" button at some point. I've toyed with the idea of a scrolling credits screen inspired by "waves" of immigrants in Dwarf Fortress, heh.

**Comment by AnonymousMeerkat** [comment]
I'm perfectly fine with that idea =)

**Comment by 3000Lane** [comment]
yeah its ok :)

**Comment by Cervator** [comment]
Thanks guys :-)

@NowNewStart ?

**Comment by nnsdev** [comment]
Don't have a problem with it :)

Date: Tue, 16 Jul 2013 19:56:30 -0700

**Comment by Cervator** [comment]
@NowNewStart - I appreciate the enthusiasm but really would like it if you could do these sorts of changes through pull requests instead of direct commits, and that after some _thorough_ testing:

![terasology splash site - mozilla firefox_2013-08-07_23-18-57](https://f.cloud.github.com/assets/1063833/929298/9e547ad4-ffd9-11e2-97eb-8a30da637245.png)

That also gives us an obvious point in time to review code and in cases where we aren't sure what solution to pick we can discuss it real quick to see if that's the direction we want to go in. For this one I'd heavily prefer credits in HTML comments and no strange JS that can end up just breaking instead

**Comment by nnsdev** [comment]
Mhm, I saw the error, I closed the <p> Tag in the footer and didn't inbound the onclick.
