### ISSUE TITLE
Add "Launcher" download button or change the normal download destination

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#35]
Now that the launcher project is going stable - this needs to wait just a bit on @mkalb till the target link is live, should be something like:

http://jenkins.movingblocks.net/job/TerasologyLauncherStable/lastSuccessfulBuild/artifact/build/distributions/TerasologyLauncher.zip

**Comment by mkalb** [comment]
Please use this URL:

http://jenkins.movingblocks.net/job/TerasologyLauncherStable/lastStableBuild/artifact/build/distributions/TerasologyLauncher.zip

https://github.com/MovingBlocks/TerasologyLauncher/releases

**Comment by Cervator** [comment]
New link works, but GitHub must be caching the old version - wonder how long that lasts. Verified it in code and by uploading the whole site to test hosting.

We might want to create a second download button sometime that'll directly download the base game without the launcher, some people seem to dislike launchers or be in situations where they won't always work (bring home via USB stick or so)

I do like the GitHub release page too, wonder if we should use that one instead. But I guess that'll change with newer releases.

**Comment by nnsdev** [comment]
We could make one Download Button, and when the user clicks on, a Windows opens and askes whether he wants to download the Launcher or directly the game :)

**Comment by Cervator** [comment]
Nah, too complicated, better to either have two buttons or a sub-divided button

Download
Launcher / Game

Or maybe eventually we'll have enough options for a new Download submenu

**Comment by nnsdev** [comment]
Or we make a new Layout and let 2 new buttons appear on the right side when clicking or hovering on the "Download" Button.

**Comment by Cervator** [comment]
Main layout related tweak I'm interested in is #20 - we probably should use a download sub menu page. Stable launcher, stable game, latest dev build, and a back button. Maximum flexibility for adding more downloads later without worrying about customizing existing buttons or logic.
