### ISSUE TITLE
Download sub-menu

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#36]
As discussed in #35 we could use a separate Download page:
- [x] Download Launcher
- [x] Game Client (stable)
- [x] Game Client (latest)
- [x] Module Downloads
- [x] Back

Will take making a few more buttons. Module Downloads would eventually be a link to http://terasologymods.net or so, not ready yet

**Comment by nnsdev** [comment]
Np, will make in a few minutes :)

**Comment by nnsdev** [comment]
WIll make PR in a few minutes.
PS: Why does this repo has the name "movingblocks.github.com"? It should be "terasology.org" :)

**Comment by Cervator** [comment]
It is a special name - a repo named the exact same as a user/organization then .github.com will be hosted by GitHub at that address. Then if you add in a little CNAME file with an actual domain in it (terasology.org) GitHub will add in some magic to redirect to that address (and direct requests to that domain when it is pointed to a particular GitHub address)

We thusly do not actually host the splash site outselves, GitHub does. Which means if our webhost melts, splash site stays up :-)

**Comment by nnsdev** [comment]
Ah okay, I understand. Actually I have the Problem that I can't upload and make a PR. I tested it and it works, can you create the Buttons "Launcher","Stable Release", "Latest Release" and "Modules" + the html file "download_content.html"? Then I can make the changes :)

**Comment by Cervator** [comment]
That's the whole change :D

I'd rather fix what's wrong - teach a man to fish, feed him for life, and all that. If you have problems like that hop on IRC and we'll sort it out.

I also am not on top of the buttons & font - we might want to redo all of them sometime with a little mini-guide in place for exactly how to make said buttons. Or much much better yet: #3

**Comment by nnsdev** [comment]
IRC is a Problem. I'm just using my Phone's Internet with Tethering so I dont' know whether my phone has a so low ping to not disconnect(Data Connection shortened :( )

**Comment by Cervator** [comment]
Okay, then just talk back and forward here on in the forum :-)

In the forum more people might notice and be able to help
