### ISSUE TITLE
Tone down the IE warning a little bit / fix that it can't be closed?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#4]
Currently when a user opens the splash site at http://terasology.org in IE a fairly good sized disclaimer banner appears encouraging the user of another browser. While that's good advice, and the site does indeed not work very well in IE (background doesn't change, for instance), we might want to make the banner just a little less dramatic :-)

The banner also doesn't click away anymore, I think that used to work pre-Ajax, but am not totally sure (I tested on Win7 64-bit with IE9). That the background doesn't change _does_ predate the Ajax and was a problem even before. I'm not sure if there's a good way to make it work, but if it _can_ be made to work better with Ajax etc then maybe we can remove the banner entirely instead!

It works on Android still, cool!

**Comment by nnsdev** [comment]
Decreased it, later in my fork :)

**Comment by Cervator** [comment]
Banner is more the right size now. Would like the icons re-added in smaller versions please, they did look good just very "loud" at that size :-)

**Comment by nnsdev** [comment]
Yeah, looking to manage it :)

**Comment by nnsdev** [comment]
Now it's no banner, it's just text in the image with Browser Images :)

**Comment by Cervator** [comment]
Cool - looks like the Safari icon isn't transparent, so it gets a white background.

Maybe for the text try something like "IE doesn't fully support all features for this page. For a better experience use: [icons]" ?

Would be nice if we could get that "hide disclaimer" 'x' working again, but that's kinda fancy :-)

**Comment by nnsdev** [comment]
Yeah, Google doesn't has transparent ones.
Okay, let me edit :)

**Comment by Cervator** [comment]
I fixed the Safari image and pushed the new text. Closing this - going to open an optional issue for re-adding the actual banner part (so dark backgrounds won't hide the text) contingent on being able to hide it like how the original one did it :-)
