### ISSUE TITLE
Change "Play" button to "Play (PC)"

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#40]
Referred a user to the splash site and he was sad the play button didn't work - on his phone. Whoops. We probably should be pointing that out ...

(Ideal dependency on #3 - if we had that I could just do this in less time than it took to write this issue)

**Comment by nnsdev** [comment]
Should I make it advanced that Mobile Users get an error message?

**Comment by Cervator** [comment]
If you can detect them when they click the play button and display a mobile friendly error instead, sure :-)

I don't think we need a preemptive error before a user clicks the button
