### ISSUE TITLE
Add more videos

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#45]
Splash site has sat alone for quite a while until it was just finally overhauled - there's a bunch of videos new since then, we should pick a few interesting ones and update the ones listed
##

**Comment by neoascetic** [comment]
I am thinking that instead of hardcode interesting videos we could load them dynamically - using Youtube API - from a particular playlist, for example. Same for backgrounds - via Flirck or other service API. 

Using this approach adding new stuff to splash site would be as easy as click "share" button - with no need in dealing with all this HTML and stuff.

However, this idea should be discussed in its own issue.

**Comment by Cervator** [comment]
Good call!

Is there a particular widget you think we'd use, or do we still place where to fill in thumbnails?

I suppose we need to tidy up the playlists then :-)

Flickr (or similar) idea also sounds interesting, although I (selfishly, heh) wonder what would happen in an office environment where Flickr is blocked. Missing videos is one thing, missing backgrounds has a tad more impact :-) Or do you think the way it would work would not directly serve content from Flicker (or some other site) ?

**Comment by neoascetic** [comment]
We may use one default background image served with the site and try to change background if Flirk (or any other site - suggest yours!) is available.

About Youtube - I think that this stuff easier to code by hands.

**Comment by neoascetic** [comment]
Or... why not leave on site only link to youtube channel since all videos link to it? Or we may replace thumbs with actual players to allow view gameplay on the site without leaving it.

**Comment by nnsdev** [comment]
We should open a place where everybody can upload his screens, and it rotates trough all them.

**Comment by Cervator** [comment]
@NowNewStart Noooo - allowing open publishing like that leads to dark places ;-)

@neoascetic - some of the big videos are done by others (the biggest by Gronkh is near a million hits) and while we could put them in different playlists they might end up somewhat more hidden than nicely categorized on the splash site ... but that's a pretty weak argument on my part :-)

I don't really know what the best option is, but either way we need somebody to sort out videos - either on Youtube or in thumbnails. Actual tiny players would be cool too. Really I'm open to ideas for whatever will work nicely.

**Comment by skaldarnar** [comment]
We can always add more videos, but for that we'd need to make videos in the first place. I don't think we need an issue for that, though.
