### ISSUE TITLE
Remove "Modules" at "Downloads"

### ISSUE THREAD

**Issue by mkalb** [MovingBlocks/legacy-website#48]
Remove button "Modules". The page "http://terasologymods.net/" is empty.

**Comment by nnsdev** [comment]
I am asking why :-(

**Comment by Cervator** [comment]
Haven't heard from Phillaxx for a while, but it might be the site is just hibernating till module distribution is more mature.

It might be an idea to instead direct to the Modules tab in Jenkins for now.

**Comment by nnsdev** [comment]
I could also make one, for uploading, possibility to update etc. Their mods.
