### ISSUE TITLE
Replace "Launcher" link with github releases

### ISSUE THREAD

**Issue by mkalb** [MovingBlocks/legacy-website#49]
https://github.com/MovingBlocks/TerasologyLauncher/releases/latest

**Comment by neoascetic** [comment]
Now it is pretty easy to change menu stuff, so instead of issue you can create a pull request

**Comment by nnsdev** [comment]
A direct download link would be better ;-)

**Comment by Cervator** [comment]
A direct download link on GitHub might be problematic as even the generic "latest" link up there ends up holding a version-stamped path to the zip. I think that's why we keep just referencing the releases page instead. Also looks nice with notes and such.

**Comment by nnsdev** [comment]
Closed as of #50.

**Comment by neoascetic** [comment]
Shouldn't links to latest and stable clients be changed too?

**Comment by Cervator** [comment]
Those are direct links to Jenkins - we don't have those auto-publishing to any sort of alternative location yet :-)
