### ISSUE TITLE
Site should handle absence of javascript better

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#51]
Reported by @mkienenb who noticed the lack of the main menu as jquery.com was disallowed by noscript :-)

**Comment by neoascetic** [comment]
Hmm, my bad. Probably I broke something since all worked good without JS before.

**Comment by Cervator** [comment]
Thanks! I'm badgering @mkienenb to provide some more details :D

Relates at least in part to the 

```
<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
```

piece. Should that be made local? :-)

**Comment by mkienenb** [comment]
I see I commented on the PR and not on the issue.   I'll make a comment here instead:

# 

It doesn't completely fix the problem.

If I allow teraslogy.org with NoScript, but disallow jquery.com, the jquery library still doesn't load and the page silently loses the menu. At worse, there should be a check and a warning if the jquery library cannot be loaded. At best, the file should be served locally so jquery.com doesn't have to be enabled nor available.

# 

Also,  It seems like there are a few reasons why not providing this locally seems like a bad idea: 
- Site might not be available
- Site might change to an incompatible version
- Site might get hacked and change to a compatible but hacked version

**Comment by neoascetic** [comment]
@Cervator nope, this file linked to CDN. Maybe we should change it to Google CDN, however.

**Comment by Cervator** [comment]
Is there a benefit in _not_ having it hosted locally? Since locally means GitHub anyway, not our webhost or anything :3

Pardon in advance for my lack of advanced html-fu on good practices etc :-)

**Comment by neoascetic** [comment]
@Cervator [here is why](http://stackoverflow.com/a/2180401/870505)

**Comment by mkienenb** [comment]
But did you read the article referenced at the bottom of [here is why](http://stackoverflow.com/a/2180401/870505)?

http://www.root777.com/appdev/does-using-google-libraries-api-cdn-give-you-performance-benefits/

So as of March 20, 2012, this wasn't helping performance, and it still leaves you all of the negatives I stated before, plus breaking the page for anyone who selectively has disabled javascript.  My suggestion is to weigh the actual benefits and actual downsides.   Benefits: unproven, possibly false, performance increase for a 96K uncompressed download.   Downsides: Unusable page when javascript is selectively disabled.

**Comment by neoascetic** [comment]
The main goal for me was not to gain any performance. It's just easy for me to link a jQuery or any other library I am using to a CDN.

If someone has javascript selectively disabled he probably knows what he is doing - and, thus, can enable javascript from CDN _selectively_ for the domain.

Anyway, this is not a big deal. Feel free to put jquery in the repo.

**Comment by Cervator** [comment]
Thanks to you both for the constructive discussion - nice to read the pros and cons :-)

It seems ultimately to be a fairly minor issue and I could go either way. But since there's an impact on one side (very rare failure to load fully for what are likely expert users) we can avoid without any serious drawbacks (might be different if we had high traffic / bad hosting - but GitHub already offers us free bandwidth) I think we should go with bundling stuff locally

I see a cloudflare entry too, for something ajax, does that degrade the site any if missing? The Google Analytics piece is a non-issue since it shouldn't impact the users even if broken

Either way no rush :-)

**Comment by mkienenb** [comment]
Just a couple of clarifications:

> If someone has javascript selectively disabled he probably knows what he is doing

But if the site looks like it is fully functional but is missing a key element (the menu system), and there's no warning when the menu is missing, there's no way for an "expert" user to know that something needs to be fixed.   This is our current situation.  If we want to continue using CDNs, then we have to detect when the CDN library isn't available and indicate it to the user.  This likely impacts your easy-of-use reason for using the CDN in the first place.

> and, thus, can enable javascript from CDN selectively for the domain.

You can't selectively enable javascript from a CDN for a domain.   If I enable javascript for jquery.com or google, then I enable all javascript library references for every site using jquery.com or google.  I don't know if that's enough to cause a site referencing a CDN to execute malicious code, but it could be.
