### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by mkalb** [MovingBlocks/legacy-website#52]
https://github.com/blog/1833-github-pages-3
##

**Comment by Cervator** [comment]
Thanks for this issue - I noticed the update and was thinking we should look at it sometime. Much better sitting in an issue here than in a forgotten browser tab at my house ... :-)

**Comment by neoascetic** [comment]
I am not sure if any of these features is interesting for us

**Comment by Cervator** [comment]
They might not individually be revolutionary, or even ideal for the main splash site, but I'm thinking the repo metadata stuff would be great for a 2nd site we need to start looking at hosting, for the Terasology org, listing summary data for all the modules :-)

The article even mentions the Netflix page I'm interested in emulating :D

http://netflix.github.io

**Comment by Cervator** [comment]
In a similar way here are more updates - that may or may not matter to us: https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0

On a related note (although not very related to this repo) I'm thinking about making another GitHub Page that may indeed use some of the more advanced features like making JSON data exposed easily to the Page framework - that would be a handy way to record module metadata for a smart listing.

**Comment by skaldarnar** [comment]
Adding more features to the website, and making use of new features offered by Github is always a welcome contribution. As this issue has aged quite a bit and does not have concrete action items to work on I'm closing it now.
