### ISSUE TITLE
Link G+ to splash site

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#54]
Ran across this while hunting for links to update

http://support.google.com/plus/?p=link_page_to_website&hl=en&authuser=0

The snippet to add is:

```
<a href="https://plus.google.com/103835217961917018533" rel="publisher">Google+</a>
```

But I'm not sure where to put it or how it might look

**Comment by neoascetic** [comment]
> Webmaster linking: If your website is already verified in Webmaster Tools, then the verified webmaster can approve a request to connect your website to the Google+ page for your business.

The alternative way.

**Comment by Cervator** [comment]
Thanks! This time through I was able to verify the site in G+ with the tweaked URL in place :-)

Also: o hai! Nice to see you around still. Lots of activity suddenly and as usual no lack of stuff to do :cake:
