### ISSUE TITLE
Launcher Subpage

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/legacy-website#55]
With bundling the JRE with the launcher we get a bunch of OS specific download packages. Thus, it would be nice to have a prettier subpage for the launcher. Requested features:
- [ ] a table/listing of different download packages. (Windows 32/64-bit, Linux 32/64-bit, Mac 32/64-bit, Plain[no bundled JRE], giving a total of 7 versions).
- [ ] propose a good candidate for users by either marking it visually or putting the detected option somewhere prominent (centered, bigger, ...). [1]
## Related

https://github.com/MovingBlocks/TerasologyLauncher/issues/259 -- Bundled JRE
https://github.com/MovingBlocks/TerasologyLauncher/pull/299 -- PR for bundling the JRE with the Launcher
## Resources

[1] http://stackoverflow.com/questions/1741933/detect-64-bit-or-32-bit-windows-from-user-agent-or-javascript
##

**Comment by jdrueckert** [comment]
Closed by #138
