### ISSUE TITLE
Standardize license one day?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#56]
We are likely aiming for ~~CC BY-SA~~ CC BY 4.0 (my mistake and later edit - SA is too GPLly) in general for all our base art resources and other things that aren't outright code going under Apache 2.0. Splash site is under BY-NC-SA as per @3000Lane from a very early version onwards (not sure how much of the original code is even left?)

https://github.com/MovingBlocks/movingblocks.github.com/commit/d455dea0825ce7c2e0e1948160bc753f7fc481ca

@shartte might be about to change it around even more.

@3000Lane - you still out there? Would you be okay with a switch to plain BY-SA sometime?
##

**Comment by skaldarnar** [comment]
Updated by #71
