### ISSUE TITLE
Change download button

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#6]
Right now there's a download menu, but with the Terasology Launcher going stable soon we should be able to link directly to its download item in Jenkins.

http://jenkins.movingblocks.net/job/TerasologyLauncherStable/

This item depends on https://github.com/MovingBlocks/TerasologyLauncher/issues/52

In the meantime it would be nice to have the download menu page removed in favor of the Download button going straight to http://jenkins.movingblocks.net/job/Terasology/lastSuccessfulBuild/artifact/build/distributions/Terasology.zip

**Comment by nnsdev** [comment]
NP. Will also do later :-)
