### ISSUE TITLE
Issues with buttons/icons in different browsers

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#61]
On checking after recent changes (on Win7, latest browsers) - may not be valid on all systems
- [x] Firefox leaves the icons in the footer invisible until hovered over by the cursor
- [x] Chrome leaves the icons in the footer "solid" regardless of hovering (usually they light up when hovered over)
- [x] IE doesn't show the menu buttons at all and has the same issue as Chrome as well (happens for me but not @msteiger - weird)

Not actually sure how old those issues are, pretty sure they've been around a while. May be time for an overhaul of the main index.html structure

**Comment by msteiger** [comment]
All errors should be fixed by now. Even the [W3C validator does not show any issues](https://validator.w3.org/nu/?doc=http%3A%2F%2Fterasology.org%2F). Any messages in the error console? Can you try on a different machine?

**Comment by Cervator** [comment]
Tried different machine. Can't replicate. Must just be my main system being weird, thanks for the patient checking! :-)
