### ISSUE TITLE
Replace soundtrack player in Flash with an HTML5 version

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#65]
If one is available but it sounds like it: https://developers.soundcloud.com/docs/api/html5-widget

When updated also update any related doc references (if indeed any). Making a note of it on https://github.com/MovingBlocks/Terasology/wiki/Project-Overview
##

**Comment by msteiger** [comment]
Yes, at least mp3 should be supported across all major browsers. A simple solution should be enough for the website:

Example: http://stackoverflow.com/a/33723330/198397

**Comment by smsunarto** [comment]
New site - closing.
