### ISSUE TITLE
Clean up DNS entries

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/legacy-website#66]
There are a few DNS entries that are no longer up to date and some others are not identical across the different top-level domains.

This can be done through the Digital Ocean web frontend.

**Comment by Cervator** [comment]
Done while I migrated the terasology.org domain off DigitalOcean in favor of NameCheap to get email forwarding to work again (was previously managed on my old GoDaddy account just with DNS on DO pointing email stuff there)

Only the .org went to NameCheap and just for the email forwards. We should probably start using the other domains when appropriate, like .net for any auto-generated droplet domains (Jenkins builders, test server, etc). I also picked up terasology.io not too long ago. DO offers "floating IPs" which we could eventually enable for the few servers using .org addresses if needed.

NameCheap DNS seems to update slower than DO.
