### ISSUE TITLE
Add Discord icon/invite

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#69]
I set us up with Discord for a public "fancy" chat like Slack, but meant for anybody in an interest in playing and talking about the game (even voice chat, huzzah). So a lot less formal than Slack (dev talk only, very little off-topic) but way richer in features than plain old IRC.

We should add the icon to the splash site, using the invite link to join up: https://discord.gg/4uKbB8J

Probably of interest to @smsunarto

**Comment by smsunarto** [comment]
Noted! I will add it together with the design overhaul

**Comment by Cervator** [comment]
Closing as complete!
