### ISSUE TITLE
Make the social buttons highlight into colored versions like in the launcher?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#7]
The social buttons on https://github.com/MovingBlocks/TerasologyLauncher currently light up into colored versions when hovered over. It would be ideal if we use the exact same passive/active social icons in both places :-)

**Comment by nnsdev** [comment]
I can try, but im not The best in CSS :-D
Edit://
Yeah, it works, but not for me. I searched trough the internet and saw messages from people that it works, but i'm trying this, and i just have the same picture, MiJyn can try to make it with Javascript, the images are in data/textures/

**Comment by Cervator** [comment]
Yeah I see the images but no working in IE/FF - but good to at least have the images handy :-)

**Comment by Cervator** [comment]
Down to just Jenkins and the blog now :-)
