### ISSUE TITLE
Create a developer oriented site

### ISSUE THREAD

**Issue by smsunarto** [MovingBlocks/legacy-website#72]
Currently we only have an end-user oriented website. We should also create a developer oriented site and link both of them together to attract potential contributors.

We should host this new developer site at http://terasology.io as @Cervator suggested.

**Comment by smsunarto** [comment]
# Requested Feature

- **Newcomer bite-size issues tracker**
We should track all bite-size issues from multiple repository and show them into one page for newcomers to have a look and try to solve. This can be done with the GitHub API such as https://api.github.com/repos/movingblocks/movingblocks.github.com/issues?labels=bite-size
- **Implement @nihal111 GitHub Button Generator**
This can work in conjunction with the previous feature. 
Link: http://nihal111.github.io/2017/07/05/github-jquery.html

**Comment by nnsdev** [comment]
Might hack something together on my train ride on tuesday. I would use Vue for it and a CSS framework like Bulma.io or MaterializeCSS so it can also be hosted on github pages.

**Comment by nihal111** [comment]
Fiddled around with the Github API a bit
https://api.github.com/organizations/4554375/repos?page=1&per_page=100 and https://api.github.com/organizations/4554375/repos?page=2&per_page=100 list all the repos under the Terasology org. 
Can iterate through all of these to find contained issues and then sort them according to labels.

**Comment by skaldarnar** [comment]
We have this in form of the Adventure Site / Tutorial Journey now: https://github.com/MovingBlocks/AdventureSite
