### ISSUE TITLE
Improve author informations

### ISSUE THREAD

**Issue by smsunarto** [MovingBlocks/legacy-website#73]
Create a better author information to be inserted into a blog post. Information such as (but not limited to) avatar, short description, and GitHub user page.

**Comment by skaldarnar** [comment]
This would be a nice gimmick if it would take the respective information from Github automatically. However, I do think just being able to list a bunch of names is just fine, and in the end we all represent The Terasology Foundation on our blog :nerd_face: 

Closing this as "active" issue, but please feel free to re-open or just submit a PR if there's a simple and neat solution for this.
