### ISSUE TITLE
Create a template blog post to announce play tests

### ISSUE THREAD

**Issue by smsunarto** [MovingBlocks/legacy-website#74]
On an upcoming release, we usually conduct a play test so that players and contributors can help find issues and give suggestions to improve the gameplay.

Currently, we only announce future play tests on our social media accounts and forums. We should also announce this on our website. A template blog post will make this announcement process easier.

- [ ] Header Image (Art) 
- [ ] Written Information

Banner image should contain:
1. A text that says "Play Test Announcement"
2. Our mascot (Gooey)
3. Our logo (Terasology)

Written information should contain:
1. Time (Date, Hour, Timezone).
2. Test objective.
3. Release file download.

CC: @Cervator

**Comment by skaldarnar** [comment]
Our main channel of communication is our Discord server. We announce play test sessions in the `#announcement` channel to reach interested players.

In addition, play-test sessions should also be mentioned in our regular TeraSaturday posts.
