### ISSUE TITLE
Change "Gameplay" to "Videos" and add video links

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#8]
Maybe instead of using buttons we should have some category labels like "Lets Plays", "Gameplay showcases", "Dev HowTos" with videos grouped below as tiny thumbnails with a simple caption?

Lets plays should start with Gronkh's video, then include whichever other ones make sense (like the recent one at http://www.youtube.com/watch?v=E4TbqZ0TMXg)

Gameplay showcases should include the crafting tutorual, the Leap video, at least one highlighting the crazy 3d wizardry from @begla lately, maybe one with physics / explosions ...

Dev HowTos should include A'nW's block shape tutorials, any setup videos for general development, and so on

Sidenote: we should group video playlists on the https://www.youtube.com/user/MovingBlocks channel into the same categories

**Comment by nnsdev** [comment]
Wouldn't it be too full?

**Comment by Cervator** [comment]
If they were full-size buttons, yeah. Think thumbnails not much bigger than the social buttons in three rows under a narrow header each. Or something like that.

**Comment by nnsdev** [comment]
Then give me a list of the videos i should add. :)

**Comment by Cervator** [comment]
A few of the more recent ones from https://www.youtube.com/user/blockmaniaTV/videos?view=0 along with http://www.youtube.com/watch?v=-cdhxguyMpA on Crafting from @small-jeeper (@skaldarnar also released a tutorial in German - hmm, wonder if we can do flags to show/hide videos in different languages)

Hunt down some of the videos posted in the miniions thread by Overdhose

Dev howtos: Block shape tutorial part 1: https://www.youtube.com/watch?v=BM219wj0v6Y - we've got to have another video or two like that

Lets plays: Gronkh's video, of course. This one as well: http://www.youtube.com/watch?v=E4TbqZ0TMXg plus any relatively recent high hit count videos you can find around

There are more videos, it is just hunting them down. If we can get the initial setup of the page I can add/suggest more when they come up :-)

**Comment by Cervator** [comment]
Closing in favor of new design idea
