### ISSUE TITLE
Create and add video showcasing Skaldarnar's Gothic Village world

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/legacy-website#9]
Maybe @Skaldarnar can record one, or somebody else can download the full game + saved world and make something nice. Catch the fact that there are "smoke blocks" by chimneys, I nearly missed that ;-)

http://nanoware.org/terasology/GothicVillageWorld.zip - right game build with world already included

http://forum.movingblocks.net/threads/screenshots.155/page-6#post-7188 - some of the related posts

When done the video should be linked from the splash site's video section, probably as a gameplay showcase?
##

**Comment by skaldarnar** [comment]
Closed as outdated. We have other interesting videos by now, and there are likely more to come with GSOC happening and such.
